### ISSUE TITLE
Cruis'n Exotica (USA) Crashing

### ISSUE THREAD

**Issue by Cibomatto2002** [m64p/mupen64plus-GLideN64#10]
Here is a DMP File of the crash.

mega:#fm/9W5ikKyR

**Comment by loganmc10** [comment]
Yes this is unfortunately a bug with GLideN64, the graphics plugin, I've reported the issue there:

https://github.com/gonetz/GLideN64/issues/1549

**Comment by loganmc10** [comment]
I disabled the optimizations that was causing the crash. The build on the site has been updated.
