### ISSUE TITLE
Jet force Geminis not working 32 bit client

### ISSUE THREAD

**Issue by CloudHaze** [m64p/mupen64plus-GLideN64#100]
Hello tried the last update 15 october 2018 32 bit client, and when loading Jet Force Geminis, with the Gliden64 plugin video, it doesnt pop up the game image, it stucks on_

Its like: init noise textures initializing, and then black screen, then I hear the intro song of the game, purple screen aftewards and music in background, thats it i cannot see any video :( 

Also tried the anglio but thats work it pops image, but very slowww. What can i do? thanks. 
I apologies for my poor grammar.

**Comment by loganmc10** [comment]
Thanks, this is an issue with GLideN64, I've tracked down the commit that caused the issue and informed gonetz, I'll close this here since it lies with GLideN64

https://github.com/gonetz/GLideN64/issues/1574#issuecomment-430268609
