### ISSUE TITLE
Emulation error causes AI in some racing games to be unbeatable?

### ISSUE THREAD

**Issue by Tasosgemah** [m64p/mupen64plus-GLideN64#101]
Not sure if this is an emulation error of some sort but i noticed that in some racing games, the first place AI player is unbeatable. You can't reach him no matter what you do and you can see him on the map going further and further away from the competition, usually finishing the race while the second place player (me) still having to race through half of the map.

I noticed this happening in Top Gear Overdrive and Lego Racers so far. In Lego Racers it only happens in single race mode, grand prix seems alright. I don't know if this happens on the real N64 with Lego but i'm pretty sure Top Gear Overdrive didn't behave this way since i finished it back in the day and i don't remember it being like this. I mean, even with the fastest car available and no mistakes, i'm still half map away from the AI.

This seems to happen in both RetroArch cores as well, including ParaLLel.

**Comment by loganmc10** [comment]
You need to confirm its not this way on a real N64 before this can be a valid issue
