### ISSUE TITLE
Jet Force Gemini Problems

### ISSUE THREAD

**Issue by TemporalAgent** [m64p/mupen64plus-GLideN64#102]
Jet force Gemini loads but there is not picture unless I turn on widescreen. Then only the sides appear.

**Comment by loganmc10** [comment]
I can't reproduce this, works fine on my PC

**Comment by TemporalAgent** [comment]
Must be something on my end. Thanks

**Comment by TemporalAgent** [comment]
That did the trick. Thanks for the help.
