### ISSUE TITLE
Alt+Enter doesn't work

### ISSUE THREAD

**Issue by GyoMan** [m64p/mupen64plus-GLideN64#104]
Alt+Enter doesn't work with Nov 5 2018 version.

**Comment by loganmc10** [comment]
Like to go into full screen? Can you try clicking in the window and then trying the combo?

**Comment by GyoMan** [comment]
I have set it up to start a game at fullscreen. If i click in the window Alt+Enter works. It seems that the window loses focus when the game starts.

**Comment by GyoMan** [comment]
Win7/64

**Comment by Krusher97** [comment]
Seems to be working for me on Nov 10 build on windows 7 64 bits

**Comment by GyoMan** [comment]
Yes, latest version works fine!
