### ISSUE TITLE
Paper Mario - Glitched transparency on Watts attack

### ISSUE THREAD

**Issue by Krusher97** [m64p/mupen64plus-GLideN64#108]
![paper_mario-002](https://user-images.githubusercontent.com/25664221/48428733-9b810c00-e791-11e8-9913-e73ed482118c.png)

When using GlideN64, Watt's attack animation has a solid yellow rectangle on an enemy instead of being completely transparent. 
This is taken with native resolution factor set to 1.

**Comment by loganmc10** [comment]
Please file this in the GLideN64 GitHub repo, you'll get a much better response there. They'll probably ask you for a savestate
