### ISSUE TITLE
Inquiry - Blur feature

### ISSUE THREAD

**Issue by Exequiel3k** [m64p/mupen64plus-GLideN64#109]
Hey,
First and foremost, thanks for making such a great package available to us all :)

Bare in mind, I’m aware there exists smoothing/sharpening within the settings, but I wanted to know if it was possible to add a user-defined blur option which lets us blurr the image to a certain level (i.e. less crisp images)?

I’m asking this because everything seems “just too pixel-sharp at times”😅 and was hoping I could tone it down and replicate the “bluriness of old ntsc/crt screens”..

Also, I’m aware retroarch has shaders but this emulator is just too darn good to switch for bluriness :p

**Comment by loganmc10** [comment]
This is something that would be handled by the graphics plugin (GLideN64), I suggest you open an issue there:

https://github.com/gonetz/GLideN64

Any changes made there are automatically incorporated into this project
