### ISSUE TITLE
Flame Effect on Lava Piranha Boss in Paper Mario Not Rendering Correctly

### ISSUE THREAD

**Issue by BatteryPine** [m64p/mupen64plus-GLideN64#11]
Image of the effect in the latest build of m64p http://i.imgur.com/AAx4Ymk.png
Image of the effect in Project64 with the latest build of GLide64 http://i.imgur.com/qgoCR4p.png
Settings for m64p http://i.imgur.com/GBjhU9Z.png
Settings for Project64 http://i.imgur.com/YsLV4em.png

I tried enabling N64 Depth Compare in m64p, but the results were still the same. I've also included a zipped folder containing a save file before the boss and a save state during the fight. 
[Paper Mario (U) [!].zip](https://github.com/m64p/mupen64plus-GLideN64/files/1290046/Paper.Mario.U.zip)

**Comment by loganmc10** [comment]
This is caused by having "EnableCopyAuxiliaryToRDRAM" enabled. It looks like you have that enabled in PJ64 as well, but I don't have a save state to test there, in any event, disabling that setting should fix the fire.
