### ISSUE TITLE
Request: Rewrite GUI from QT to SDL

### ISSUE THREAD

**Issue by extherian** [m64p/mupen64plus-GLideN64#114]
It is my understanding that since Mupen64Plus uses SDL for its controller inputs, while M64P uses QT as its frontend, thus making capturing mouse input impossible. I have opened an issue on the Mupen64Plus repository asking them to implement an API that would allow for mouse capture from a QT window, in much the same way that keyboard capture is possible. However, my request has gone ignored.

Since upstream does not seem interested in changing the input plugin of Mupen64Plus to be compatible with a QT frontend, I'd like to request that an SDL rewrite be considered as a goal for the far future. Otherwise, M64P will never be suitable for mouse/keyboard users, especially considering so many N64 games require precise input. 

I am not interested in buying a controller for this purpose as I find mouse/keyboard input far more comfortable. For now, I'll have to go back to using Project64, the only active N64 emulator with mouse support.

**Comment by loganmc10** [comment]
Sorry, it just won't happen, the GUI will stay in Qt
