### ISSUE TITLE
GLideN64 not loading at all

### ISSUE THREAD

**Issue by HenWilOliPin** [m64p/mupen64plus-GLideN64#115]
Set up a fresh Windows 10 install this morning, went to download m64p and I can't load anything with GLideN64. Angrylion works, but when I have GLideN64 selected, it says the normal "Init Noise Textures. Please Wait..." but then nothing happens and it stays on the black screen, if I leave it alone for a lil while the standard "not responding" cycle happens. Before it says "not responding", I can still open different settings without any issues, but if I fullscreen nothing responds and I have to alt+tab out, and trying to close out with X or rightclick + close window does nothing at any point, I have to end task with task manager. No idea what's going on, tried with DK64 and SM64, both respond same way. Will post log from DK64 in next comment. No settings changed other than picking between GLideN64 and angrylion
EDIT: if you guys want me to screencapture what I'm talking about let me know

**Comment by HenWilOliPin** [comment]
Core: Goodname: Donkey Kong 64 (U) [!]
Core: Name: DONKEY KONG 64      
Core: MD5: 9EC41ABF2519FC386CADD0731F6E868C
Core: CRC: EC58EABF AD7C7169
Core: Imagetype: .z64 (native)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: USA
GUI: using Video plugin: 'GLideN64' v2.0.0
GUI: using Audio plugin: 'Mupen64Plus SDL2 Audio Plugin' v2.5.0
Input: Using auto-config file at: 'C:/Users/Henry/Downloads/mupen64plus\InputAutoCfg.ini'
Input: Using auto-config file at: 'C:/Users/Henry/Downloads/mupen64plus\InputAutoCfg.ini'
GUI: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
GUI: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Input: 1 SDL joysticks were found.
Input: Using auto-config file at: 'C:/Users/Henry/Downloads/mupen64plus\InputAutoCfg.ini'
Input Error: No auto-config found for joystick named 'Swiftpoint Z' in InputAutoConfig.ini
Input: N64 Controller #1: Forcing default keyboard configuration
Input: Using auto-config file at: 'C:/Users/Henry/Downloads/mupen64plus\InputAutoCfg.ini'
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
RSP: RSP Fallback disabled !
Core: Using video capture backend: dummy
Core: Game controller 0 (Standard controller) has a Memory pak plugged in
Core: Game controller 1 (Standard controller) has a Memory pak plugged in
Core: Game controller 2 (Standard controller) has a Memory pak plugged in
Core: Game controller 3 (Standard controller) has a Memory pak plugged in
Core: Using CIC type X105
Audio: Initializing SDL2 audio subsystem...
Audio: Audio device 0: 4 - LG ULTRAWIDE (AMD High Definition Audio Device)
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Core Warning: OSD not compatible with OpenGL core context. OSD deactivated.
Core: Initializing 4 RDRAM modules for a total of 8 MB
Core: Starting R4300 emulator: Dynamic Recompiler

**Comment by loganmc10** [comment]
What graphics card do you have? And what version of the driver for your graphics card?

**Comment by HenWilOliPin** [comment]
Radeon RX 580, version 22.19.677.257
Should be up to date, always have to update when I fresh install cuz without updating my resolution is atrocious. IDK what version it was when m64p worked, I guess if a new driver came out last night it could be different

**Comment by loganmc10** [comment]
Hm yeah it should work. Hard to say what might be up. If I was you I would try playing with some of the GLideN64 settings.

Recently N64 Depth Compare was set to be enabled by default, you could try disabling that as a start.

You said it used to work on this same PC correct?

**Comment by HenWilOliPin** [comment]
Yeah, literally overnight this started happening. I messed with AR and fullscreen, which are the only things I usually change, and changed recompiler but nothing made a difference. Will try depth compare when I get home

**Comment by HenWilOliPin** [comment]
Disabling N64 Depth Compare worked! Did you change that default yesterday? lol

**Comment by loganmc10** [comment]
It was changed in GLideN64 a few days ago yes. Kind of curious that it doesn't work on your PC. You should file a bug in the GLideN64 GitHub repo if possible
