### ISSUE TITLE
Lack of changelog, forums, etc.

### ISSUE THREAD

**Issue by jonsn0w** [m64p/mupen64plus-GLideN64#120]
Hello, I'm not sure if this is the place for this. I'm a huge fan of m64p, but it's nearly impossible to follow the progress of updates as there's no changelog, no forum, no discord, nothing. There are several questions I had that I'm unsure where to ever get a proper response, so I'm trying here. 

1. Does m64p use GlideN64 3.0 or 2.0 still?
2. Is there any way to fix the black grid lined skyboxes in Megaman64? It seems to be an issue on every emulator with every plugin. 
3. Although m64p works great out of the box, is there anywhere to learn which settings could be tweaked in order to have an even greater graphical experience? 

Thanks in advance!

**Comment by jonsn0w** [comment]
Wow thank you for such a fast and informative response! I wish you all the best and thank you for your awesome project!

**Comment by loganmc10** [comment]
No problem at all :)
