### ISSUE TITLE
Latest version 12/1 crashing

### ISSUE THREAD

**Issue by GyoMan** [m64p/mupen64plus-GLideN64#122]
While the previous version works fine, this version from 12/1 starts loading a rom, inits noise textures and drops back to main screen. No error messages.

Tried with many different roms both on window & fullscreen modes.

Win7/64 with AMD drivers 19.1.1 (latest)

**Comment by loganmc10** [comment]
The latest build incorporated a new dynamic recompiler. It appears the 64-bit version is not working. I opened an issue here: https://github.com/mupen64plus/mupen64plus-core/issues/603

For now, you can use the 32-bit Windows build, it should still work.

**Comment by GyoMan** [comment]
32-bit works fine, thanks! Note that when you enter fullscreen the window loses focus so you have to click on it to be able to use Alt-Enter to exit fullscreen. It also happened a few versions ago and it was fixed back then.

**Comment by loganmc10** [comment]
64 bit version should be working again, can you confirm?

**Comment by GyoMan** [comment]
Now 64-bits works fine. Thanks!
