### ISSUE TITLE
Zelda Ocarina of Time graphic bug

### ISSUE THREAD

**Issue by KingOfHyrule** [m64p/mupen64plus-GLideN64#13]
Hey! I really like your approach to mupen64plus + GlideN64, so I started to use your fork and found something funky using GlideN64.

Basically, there are some 2d elements (textures?) missing:
![01](https://user-images.githubusercontent.com/31485246/30508704-776fc6a6-9a73-11e7-8f36-31eba2f54113.jpg)
There should be a fence here (I can send another picture with the correct rendering if you're not familiar with the game).

![02](https://user-images.githubusercontent.com/31485246/30508706-7ae29b56-9a73-11e7-9193-615d7fa05263.jpg)
![03](https://user-images.githubusercontent.com/31485246/30508708-7ef8d6ec-9a73-11e7-8fde-fd7cd9a981db.jpg)
Pretty obvious.

All of this doesn't happen on angrylions plugin, and I'm using default settings for GlideN64, except for antialiasing (MSAA x8) and 2x internal resolution. Note that it also doesn't happen on Project64 + GlideN64 (latest WIP as of 13/09/2017, same date as when I downloaded your fork, haven't tested the latest commits you made).

I haven't gone very far in the game yet, so this may not be the only area with missing graphics. Up to this point, I haven't noticed any other problems, aside from a bit of stutter/hiccup in sound (music and SFX) when going in/out of the start menu (item subscreen) - should I make another issue for that?

Some relevant info:
PC specs: i5 3570 @ stock; NVIDIA GTX 750 1gb (384.76 drivers); 12gb RAM; win 10 updated.
ROM version 1.2

PS: I don't know where stuff such as save states and game saves are stored with your fork, and the "save to..." option never allows me to make a savestate on a custom folder because it says the file name is invalid - I have no idea why (another issue to open, perhaps?). So, if you need a save state, please tell me where these stuff is stored and I'll gladly send one for you.
:)

**Comment by loganmc10** [comment]
Let's deal with the missing items first. A save state would be really helpful. They should be stored in C:\users\you\AppData\Roaming\Mupen64Plus\save\Game Name.st0

**Comment by KingOfHyrule** [comment]
[zelda save states.zip](https://github.com/m64p/mupen64plus-GLideN64/files/1309584/zelda.save.states.zip)

Here you go. Sorry if that took a while, I don't have a lot of spare time, but definitely want to help as much as I can.

**Comment by loganmc10** [comment]
Huh yep I can reproduce this. Only happens in GLideN64 in HLE mode, I'll track down the commit that broke it and report it to GLideN64

**Comment by loganmc10** [comment]
I corrected the issue with the savestate saving and reported the GFX issue to GLideN64, can this be closed?

**Comment by KingOfHyrule** [comment]
Sure, you can close it. I'll keep an eye on the issue open in GlideN64.

Is the fixed savestate build already available in the download page? I'll test it just in case.

**Comment by loganmc10** [comment]
Yeah it's on the download page
