### ISSUE TITLE
GUI stops working when using windowed mode

### ISSUE THREAD

**Issue by KingOfHyrule** [m64p/mupen64plus-GLideN64#15]
Steps to reproduce: start a game, stay in windowed mode maximized (I'm not sure this also happens when the window is small), try to use the GUI a few times, and after a few minutes it stops working. Functions still work through hotkeys, but the GUI doesn't work and shows nothing when you click at it.

**Comment by loganmc10** [comment]
Can you give me details about your setup? (OS, graphics card, 32 or 64 bit build?)

**Comment by KingOfHyrule** [comment]
Sure:
i5 3570 @ stock; NVIDIA GTX 750 1gb (384.76 drivers); 12gb RAM; win 10 updated; 64 bit build

**Comment by loganmc10** [comment]
I couldn't reproduce this, did it happen more than once for you? If so, are there are more specific details on how to reproduce it (like what game you are playing, etc..) I have a similar setup (Windows 10 with Nvidia card)

**Comment by KingOfHyrule** [comment]
Okay, steps to reproduce are a bit weird and surprised me, maybe it's not the GUI's fault...
1) open mupen and start a game;
2) open paint (classic one), and click "save as jpeg", do whatever after;
3) go back to mupen, the gui doesn't work.

I actually stumbled upon this problem when editing the screens for the other issue, so I'm not sure it's worth fixing, since the GUI works fine if I just stay in mupen.

**Comment by loganmc10** [comment]
Huh, I could reproduce this! How strange, just to confirm we are experiencing the same issue. The GUI actually works, but the menu items are "behind" the game window, can you test this? Go File-> and click right under it (where "Open ROM" would be), does it open a file dialog?

**Comment by KingOfHyrule** [comment]
Yep, that's exactly what's happening here, I can open the dialog.

**Comment by loganmc10** [comment]
Yeah that's really strange, I'll look into it a bit but I wonder if it's some kind of bug in Qt

**Comment by loganmc10** [comment]
@KingOfHyrule can you retest this? I just tested and I couldn't reproduce it anymore. Hopefully it was just some Qt or Windows bug that has been fixed by a patch

**Comment by KingOfHyrule** [comment]
Tested again, it no longer happens.

Closed  :)
