### ISSUE TITLE
USB gamepads never reconnects if disconnected during game

### ISSUE THREAD

**Issue by KingOfHyrule** [m64p/mupen64plus-GLideN64#16]
I was using a regular xbone controller with a faulty USB cable, and so my controller disconnected during session. The thing is that I tried to reconnect it with a good cable, but the emulator didn't seemed to recognize it anymore, so I had to do a savestate and reopen it, since I couldn't control the game.

I'm not sure, but if you try to fall back to the keyboard input while the game is running, it doesn't work, so you need to restart mupen (close and reopen) to change the input from the USB to the keyboard or whatever.

**Comment by loganmc10** [comment]
Yes I've run into this many times, my house is full of messed up USB cables that my kids have destroyed. I'll try and sort it out, it's something up with the input plugin

**Comment by loganmc10** [comment]
This should be fixed now, can you re-test and close if resolved?

**Comment by KingOfHyrule** [comment]
Sorry for the delay

It's fixed, thanks!
