### ISSUE TITLE
Feature request: multiple bindings for the same buttons

### ISSUE THREAD

**Issue by KingOfHyrule** [m64p/mupen64plus-GLideN64#17]
It would be nice if we could bind multiple keys for the same button. For example, the C buttons could be mapped to both an analog stick and a D-pad, so you could use the buttons precisely (D-pad) or faster (stick) depending on the situation.

If possible, also allow for multiple devices, e.g. USB controller on primary + keyboard on secondary.

Here's a simple draft:
![sem titulo](https://user-images.githubusercontent.com/31485246/30528445-70412fb8-9c09-11e7-91ac-4b801c3700f7.jpg)

**Comment by rafapetrucci** [comment]
It would be awesome! I also wanted to assign the Z button on L2, but also on R2 as well (PS3 controller), so if the secondary controller accept the same controller would be perfect.

**Comment by loganmc10** [comment]
Unfortunately the input plugin (https://github.com/mupen64plus/mupen64plus-input-sdl) doesn't support any of this.

It only allows 1 real controller to be mapped to each N64 controller, and it only allows 1 real button/key/axis mapping per N64 button/axis (unless there is some feature I am unaware of, I took a brief look through the code)

So the input plugin would need to be modified to support this, then I could modify the GUI to support configuring it all

**Comment by KingOfHyrule** [comment]
Should I make the request directly to the plugin repo? 
I think this would be a very nice feature to have, but if it's too complicated to implement then we can just forget about it :D

**Comment by Krusher97** [comment]
![input plugin](https://user-images.githubusercontent.com/25664221/31809106-c36c09bc-b593-11e7-8bfc-6d55005e22ca.png)
After setting up my controller I noticed this mapping. It seems the input plugin does support different inputs for the same button on the same controller. I got it by setting it to automatic.

**Comment by loganmc10** [comment]
Hm yes it looks like you're right. I'll need to see if it also supports mixing keyboard and game controller inputs for the same player. I'll add this to the GUI but I can't promise how soon

**Comment by KingOfHyrule** [comment]
Okay, so I'll just wait for your implementation and, if necessary, make a request on the input repo.

**Comment by loganmc10** [comment]
Ok so I just tested and yes, it actually does support having a gamepad button/axis and a keyboard key assigned to the same input. There is definitely no way to assign 2 different gamepad's to the same player, but you can mix and match 1 gamepad and the keyboard. You can also have 2 gamepad buttons assigned to the same N64 button.

So now that I know it's possible, I'll get to work on adding the "secondary" column

**Comment by KingOfHyrule** [comment]
Nice! Mixing both gamepad and keyboard can also be useful in case your gamepad gets busted while playing (e.g. fall into pieces from your hand or whatever extreme situation you get in :p ), so you can at least save the game or do whatever you need to do in the game with the keyboard, before closing the emulator and figuring out the gamepad situation.

I know it's an edge-edge-edge case, but most (all?) of it can be sorted with the implementation suggested, so I think it would be nice to have, if possible :)

**Comment by loganmc10** [comment]
Ok I've implemented this, the bills on the website has been updated. Please give it a try and keep an eye out for any bugs.

The config file doesn't support having a secondary input without a primary. So if you try to add a secondary input where there is no primary, it'll make it the primary. If you remove the primary and a secondary exists, it'll move the secondary to primary, etc..

**Comment by KingOfHyrule** [comment]
Okay, report from build  5732f6e69 (2017-10-22):

Multiple bindings on the same gamepad - check
Mixed bindings between gamepad (primary) and keyboard (secondary) - check
When disconnecting gamepad (primary), still able to use keyboard (secondary) - check

This covers all use cases I can think of. Thank you for this  :)

If you want to test any other possible scenario, just let me know and I'll try it. But as far as I can tell, this can be closed.
