### ISSUE TITLE
GLideN64.custom.ini not working?

### ISSUE THREAD

**Issue by Tasosgemah** [m64p/mupen64plus-GLideN64#18]
Seems like any change i do to this file it doesn't have an effect. This file is useful to make per-game changes for the GlideN64 plugin. In PJ64 it works but not in Mupen. The "EnableCustomSettings" option in the video plugin settings is checked.

**Comment by loganmc10** [comment]
Can you post the contents of the file? And where is the file located? Is it in the same folder as mupen64plus-gui.exe?

**Comment by Tasosgemah** [comment]
Yes, same folder. 

Contents: https://pastebin.com/0sKuKiKF

The same file comes with the standalone GlideN64. I use it for PJ64. Normally, if i add something like 

[WAVE RACE 64]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8

It should make the game use less obnoxious borders. That's what i used to do in PJ64. But now that i use m64p more i need to paste my custom settings there but they won't work.

**Comment by loganmc10** [comment]
Can you try replacing the spaces in ```WAVE RACE 64``` with %20 like ```WAVE%20RACE%2064```

**Comment by Tasosgemah** [comment]
Oh, that works.

I assumed i didn't have to change anything in my already applied settings because they were working on PJ64. Guess i had to edit them for Mupen. Pretty stupid of me i didn't try it.

Thanks!

**Comment by loganmc10** [comment]
Yeah each project has its own INI parser, and the mupen one is not very forgiving lol
