### ISSUE TITLE
Request: Save core settings per game

### ISSUE THREAD

**Issue by Tasosgemah** [m64p/mupen64plus-GLideN64#19]
There is already a way to save graphics options per game when you use GlideN64, by editing the GLideN64.custom.ini file. However, i can't find a way to also save core options per game. For instance, i would like to be able to save different CountPerOp settings depending on the game. Because some games benefit greatly from changing it to "1" (better frame rates) but other games get timing issues or their game speed gets messed up. So you have to change the setting every time you want to test a different game.

**Comment by loganmc10** [comment]
mupen64plus.ini allows setting the CountPerOp per game, you can look through that file for examples of this. If CountPerOp=0 in the CFG it means use the value in mupen64plus.ini, or 2 by default. If you have a value other than 0 in the CFG, it will override the ini value

**Comment by Tasosgemah** [comment]
Ok i think i got it.

Thanks.
