### ISSUE TITLE
mupen64plus no working

### ISSUE THREAD

**Issue by elcorsico** [m64p/mupen64plus-GLideN64#2]
hi,
i'm french testeur of emul mupen64plus
but the emul are not working with games? ?
why
help me

**Comment by loganmc10** [comment]
I need more details, can you describe what is not working? How did you obtain the emulator? What game did you try?

**Comment by elcorsico** [comment]
hi logan , the emu load my game , but nothing to display , just black windows
show : mupen64plus: glideN64, Revision 72abac8

test in win 10 v1704 , gf1070 ,16gram but nice gaming machine
game test : mk64 and mario64 and other best games n64
thanks resolve this

**Comment by cascardian** [comment]
I can corroborate @elcorsico's experience. It happens here as well, i.e., no game will start and the window simply stays black. Win10 x64 v1703, i7-920 with a GTX 480 on 384.76. It's been like this for some time now (across different recent NVIDIA drivers). I just got the Win64 build fresh off the build-bot and nothing's changed. All other emulators, games, browsers etc., work with no issues whatsoever. If I enter a new size in the config, the window resizes normally, but it still just stays black. Neither running as an administrator nor the compatibility settings help.

I hope I can help resolve this! I'll test anything you want.

**Comment by loganmc10** [comment]
Do you hear any sound? Can you try resetting the plugin settings?

Settings->Plugin Settings->Reset All Settings (at the bottom)

If that doesn't work, can you try re selecting all the plugins? Go to Settings->Plugin Selection and set each plugin to "dummy" and then back to the plugin name

**Comment by cascardian** [comment]
The last suggestion indeed worked!

**Comment by loganmc10** [comment]
ok thanks for testing! I updated the GUI to provide a popup warning if this happens, so it should be a little more clear to people what to do in this case. @elcorsico can you try this solution?

**Comment by elcorsico** [comment]
hi logan ,the last revision are ok , test ok game run full speed
thanks
