### ISSUE TITLE
Goemon titles - Crash on loading state

### ISSUE THREAD

**Issue by Krusher97** [m64p/mupen64plus-GLideN64#22]
The latest version seems to have introduced a bunch of glitches for Goemon games. In both of them, the game crashes on loading a save state.
In Goemon's Great Adventure the framerate is extremely choppy and it affects the ingame collision detection causing the player to go right through objects you are supposed to grab.
This didn't happen on the build 2 days before the current one and doesn't happen in the old build of PJ64 I have.
Webm : https://drive.google.com/open?id=0B1sugCZh1a3ZYVJBUDM2UE5WRms
The part in the end where it stops is when the emulator crashes because I loaded a savestate.

EDIT: On further testing the save state crashing isn't limited to just all three Goemon titles. Some other titles which crash on loading a save state
Aidyn Chronicles
Chameleon Twist 1(not 2)
Doom 64
Blast Corps
Mischief Makers

**Comment by bsmiles32** [comment]
Made a PR https://github.com/mupen64plus/mupen64plus-core/pull/439 to fix that. Sorry for inconvenience.
Lots of refactorings are taking place right now, but it should hopefully settle down soon.

**Comment by Krusher97** [comment]
Its no bother. Great work on the emulator.

**Comment by loganmc10** [comment]
I don't have a chance to test today but I updated the build on the website. Can you retest? The save state issue should be fixed but I'm not sure about Goemon

**Comment by Krusher97** [comment]
Yeah the savestate issue is fixed. Feel free to close this. I'll make a new issue for Goemon's Great Adventure separately when you do.
