### ISSUE TITLE
Controller Issue?

### ISSUE THREAD

**Issue by VictorSage777** [m64p/mupen64plus-GLideN64#25]
Every time I start to boot up Pokemon Stadium 2, I get the message "Turn the N64 control deck off before attaching or removing a GB Gamepak, N64 Transfer Pak or a controller." I've tried playing around with the controller plug in settings and hard resting/booting on and off the game, but it does not work. All of my Gameboy Cartridge Selections are cleared off.

**Comment by VictorSage777** [comment]
Sorry that was my mistake, stiil getting used to the GUI.

**Comment by loganmc10** [comment]
No problem, if you think there is something I could make easier or more clear please let me know
