### ISSUE TITLE
Ignoring checksums for majora's mask rom hacks

### ISSUE THREAD

**Issue by AriaHiro** [m64p/mupen64plus-GLideN64#26]
it has come to my attention that some rom hacks in development require you to register the rom hack's checksum. something like a checkbox to just ignore them should allow you to play them without sacrificing accuracy and increase the compatibility.

**Comment by loganmc10** [comment]
I'm not really sure what you mean, where do you need to register the checksum?

What is currently the problem? Are the rom hacks not booting or something?

**Comment by AriaHiro** [comment]
they work fine in pj64 after changing the checksum in pj64s config file. without that it causes flickering in most emulators.

**Comment by loganmc10** [comment]
Can you point me to the ROM hack to try out? And perhaps the steps to get it working on Project64? You shouldn't need to update any checksum in mupen64plus to get it to work

**Comment by AriaHiro** [comment]
one is mm master quest the other is still being worked on 
https://cdn.discordapp.com/attachments/229024532369768449/370910768989995008/MajoraP-MKIII-2.0a-b-c.rar

**Comment by AriaHiro** [comment]
a quote from the developer "well, try of modify the Project64.cfg, Project64.cht & Project64.rdb
for put this crc

[DC02DD07-B97C4522-C:45]

copy this crc, copy the info of the MM normal rom CRC and paste the copied conf, chts with this CRC"

**Comment by AriaHiro** [comment]
he doesnt speak good english though

**Comment by loganmc10** [comment]
What is the problem though? Have you tried it in m64p? It seems to work fine for me, there is no flickering or anything

**Comment by AriaHiro** [comment]
like either the person reporting the bug either used an older build or the more likely case has an old graphics card as the current build lacks that problem.

**Comment by AriaHiro** [comment]
you can close the issue, sorry for wasting your time.

**Comment by loganmc10** [comment]
No problem, generally games don't need special INI/RDB entries in mupen64plus, there are a few cases though, but Majora's Mask isn't one of them.
