### ISSUE TITLE
Errors in submodules while cloning / submodule updating

### ISSUE THREAD

**Issue by Ntemis** [m64p/mupen64plus-GLideN64#27]
fatal: reference is not a tree: 27d30c778629fa41c0156352b6cde5197ea7a252
Unable to checkout '27d30c778629fa41c0156352b6cde5197ea7a252' in submodule path 'GLideN64'

**Comment by loganmc10** [comment]
Fixed now, you might have to re-clone the repository, there was a force push to GLideN64 which deleted the commit that this repo referenced but I've updated it now

**Comment by Ntemis** [comment]
Thanks
