### ISSUE TITLE
load settings on a per-game basis (ie Goldeneye multiplayer problem)

### ISSUE THREAD

**Issue by Exequiel3k** [m64p/mupen64plus-GLideN64#28]
Hey,
First of all, thank you for taking the time of making all of this possible :)

That said, I'm having issues playing Goldeneye in multiplayer (ie players 3/4 not rendering : GlideN64 issue) which "Disabling Framebuffer Emulation" seems to fix it in the videoplugin settings.. 

With that in mind, is there a way to automatically load that adjustment for this game only since it's not recommended to disable it in general..

**Comment by loganmc10** [comment]
Yes I reported this issue in GoldenEye a while ago (https://github.com/gonetz/GLideN64/issues/1173)

There is a file called GLideN64.custom.ini that controls per-game settings for GLideN64, it should be in the folder with all the other files. So for instance, to disable Framebuffer Emulation in GoldenEye you would add this entry to that file:

```
[GOLDENEYE]
frameBufferEmulation\enable=0
```

However, I just tried it with Framebuffer Emulation disabled and even that doesn't seem to fix it anymore, so you might be out of luck until that issue gets fixed in GLideN64

**Comment by Exequiel3k** [comment]
Dam, I tried it and you're right.. I also tried altering other settings without any luck. The only real way to fix this is to use angrylion-plus.dll. Could I literally tell the custom.ini to change the plug-in as well?

**Comment by loganmc10** [comment]
No, there isn't currently a way to set the plugins per game. Hopefully it can be figured out in GLideN64 soon, 4 player Goldeneye was a big part of the N64 experience for many people

**Comment by Exequiel3k** [comment]
Hopefully, since it was, was almost as iconic as Zelda OOT :p

**Comment by Exequiel3k** [comment]
Little update: disabling "EnableFragmentDepthWrite" & "EnableFBEmulation" fixed the 4 screen multiplayer issue. That said, I haven't played single player to see what other problems it could create. 

Maybe Enabling "N64DepthCompare" could somewhat aide the disabled options? 

![123](https://user-images.githubusercontent.com/33066084/32006607-39da897c-b975-11e7-8613-be35e6275628.jpg)

**Comment by Exequiel3k** [comment]
I noticed you updated the INI, so I gave it a try using the following code:

[GOLDENEYE]
Good_Name=007 - GoldenEye (E)(U)
N64DepthCompare\enable=1
frameBufferEmulation\enable=0
generalEmulation\enableFragmentDepthWrite=0

..and it worked :) 
Thx!!

**Comment by Exequiel3k** [comment]
Hey, 
I recently updated m64p and noticed the quick fix isn’t working anymore. I can no longer play 4 split screen a it’s either flashing and/or only the sky is visible on the bottom screens. Just thought I’d let you’ll know..

**Comment by loganmc10** [comment]
Yes it's a GLideN64 problem unfortunately, needs to be fixed there

**Comment by Exequiel3k** [comment]
Alright, one of the most iconic things of the N64 isn’t playlable :p 
Well, should I close this thread??

**Comment by loganmc10** [comment]
Yes it should be closed, it needs to be fixed in GLideN64, there is no setting that can fix it currently
