### ISSUE TITLE
Resident Evil 2 Missing Audio

### ISSUE THREAD

**Issue by tony971** [m64p/mupen64plus-GLideN64#29]
This one's easy to reproduce. Start up a new game. The voice over during the intro won't be there. Playing on the x64 version, Windows 10.

**Comment by loganmc10** [comment]
I can't reproduce this. Do you have anything non-standard about your setup? Have you changed any of the default settings? Is this the USA ROM? Is it v1.0 or v1.1?

**Comment by tony971** [comment]
https://pastebin.com/2Tbs0szg

My laptop has an optimus card in it with the latest nvidia drivers. USA ROM 1.1

**Comment by loganmc10** [comment]
Very strange, and you're using the latest build from https://m64p.github.io ?

Can you try renaming your mupen64plus.cfg file to something else and trying with a fresh config? I just want to see if it's some config option, although I can't see anything suspicious in yours

**Comment by tony971** [comment]
Weird. I can't reproduce anymore.
