### ISSUE TITLE
Pokemon Stadium 2 Mini-Games graphical errors

### ISSUE THREAD

**Issue by tony971** [m64p/mupen64plus-GLideN64#3]
You stated that you'd love to hear about any games that work better on PJ64, so here goes :P 

If you boot up Pokemon Stadium 2 and head to the Mini-Games menu, you can see a mis-rendered background and items that "ghost" on the screen after their objects have disappeared. I haven't found a good setting in GLideN64 to correct it.

**Comment by loganmc10** [comment]
Does PJ64 do this with GLideN64?

**Comment by tony971** [comment]
No, PJ64 works as intended with the latest WIP build.

**Comment by loganmc10** [comment]
Can you provide a screenshot? It looks normal to me, which menu specifically do you see a mis-rendered background?

![pokemon_stadium_2-000](https://user-images.githubusercontent.com/848146/29222615-7c4cacd4-7e80-11e7-8ff8-cf1edabad0f1.png)

**Comment by tony971** [comment]
![screenshot one](https://i.imgur.com/WMXrMit.jpg)

![screenshot two](https://i.imgur.com/RYy0dpP.jpg)

**Comment by tony971** [comment]
https://pastebin.com/7wDTkg0c

**Comment by loganmc10** [comment]
This is happening because of the "EnableNativeResTexrects" option.

The same thing happens for me when I enable that option in mupen64plus or PJ64 (in PJ64 it's called "Render 2D elements in N64 resolution"

**Comment by loganmc10** [comment]
If you can confirm that this also happens in PJ64, then it should be filed as a bug with GLideN64.

As an aside, I notice you also have UseNativeResolutionFactor=1 set, you probably should need EnableNativeResTexrects enabled if you're playing at a Native Res factor of 1

**Comment by tony971** [comment]
Yea, UseNativeResolutionFactor=1 seems to be the culprit. Behavior is the same on Project 64. Interestingly enough, that option is grayed out when you select native resolution on PJ64. But it's not automatically disabled. It only prevents you from changing the setting.
