### ISSUE TITLE
Hey You! Pikachu - pikachu splattered everywhere

### ISSUE THREAD

**Issue by tony971** [m64p/mupen64plus-GLideN64#30]
This one's kind of amusing. Boot up the game; go to the main menu. Pikachu is supposed to be hopping around, playing with the environment. Instead, he seems to have exploded all over the screen.

**Comment by loganmc10** [comment]
hm yep, happens in angrylion and gliden64, seems to be a bug with mupen64plus-core, I'll track down the commit in a bit

**Comment by loganmc10** [comment]
I opened an issue with mupen64plus-core

https://github.com/mupen64plus/mupen64plus-core/issues/469

**Comment by tony971** [comment]
Sounds good. No reason to have both issues open.
