### ISSUE TITLE
Close window on Stop Game

### ISSUE THREAD

**Issue by Shermer321** [m64p/mupen64plus-GLideN64#31]
Is there any way to end the application when stopping a game?

**Comment by loganmc10** [comment]
If you launch the exe and pass the command line option "--nogui" along with a ROM path it'll launch the game without the GUI elements, and close the application when the game ends, useful when used in along with a launcher like LaunchBox.

Is that what you're trying to achieve?

**Comment by Shermer321** [comment]
Spot On! Thanks.
