### ISSUE TITLE
Bitbucket Builds are not compatible

### ISSUE THREAD

**Issue by Papermanzero** [m64p/mupen64plus-GLideN64#32]
I tried to setup m64p with the bitbucket builds. 
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/downloads/
The bitbucket repository reflects the original mupen64plus github commits. 
However m64p has issues with both, the 32bit as well as 64bit builds from bitbucket.

**Comment by loganmc10** [comment]
This is expected. They aren't compatible with eachother. They are linked against different libraries.

I think the only difference is the audio plugin, and this doesn't include Glide64 or Rice

**Comment by Papermanzero** [comment]
At least the issue I saw was, that the rsp, audio and input plugin are not found. My experience is that all plugins are therefore affected.
Is it possible to make m64p compatible against the official repository? 
To be honest I wanted to switch from m64py to m64p. But without the compatibility of the regular bitbucket builds I would not be able to update to the newest in order to verify certain issues.

**Comment by loganmc10** [comment]
Sorry I meant that was the only difference between the Bitbucket builds and m64p

No, it's not possible to make them compatible. I'm not sure what issue you have with m64p though, everything is kept up to date

**Comment by Papermanzero** [comment]
Unfortunately it is not the only difference. Otherwise I would go for the SDL2 Audio plugin.
But none of the plugins are working with m64p. That is a pity, because m64p gets regular updates compared to m64py. But without the support of the official mupen64plus version m64p cannot be used (at least from my side).

**Comment by loganmc10** [comment]
There isn't really any resolution to this. The bitbucket builds are linked against SDL1. This project links against SDL2, there are probably other differences as well, there is really no way to make them compatible.

**Comment by Papermanzero** [comment]
Well, at least the main branch goes for sdl 2.0 completely.
