### ISSUE TITLE
Pokémon Puzzle League Broken effects/background textures

### ISSUE THREAD

**Issue by Arisudomo** [m64p/mupen64plus-GLideN64#33]
Pokémon Puzzle League effects may be broken on the latest (14 Nov 2017) build. Game is working completely fine with videos and effects working very well, but as the title says those textures is broken. This doesn't directly affect the gameplay, however.

![](https://cdn.discordapp.com/attachments/175554819988127744/380151407258632203/Untitled.jpg)

**Comment by loganmc10** [comment]
I can't reproduce it, looks normal to me. Do you have any non-default settings set? Can you try going to Settings->Core and Plugin Settings and checking "Reset All Settings"?

**Comment by Arisudomo** [comment]
Thank you for reaching in.
Restarted my computer and did an All Settings Reset as you said. The problem persists. Since you can't reproduce it, it may be hardware related (my hardware is quite old). Below is a new screenshot after the reset proceedures and my system specs.

![](https://cdn.discordapp.com/attachments/164547170756853760/380513537895956501/Untitled.jpg)

OS: Windows 10 Pro 64-bit (10/0, Build 14393)
CPU: AMD Phenom(tm) II X4 965 (4 CPUs), ~3.2GHz
RAM: 8192MB 
GPU: EVGA nVidia GeForce GTX 460 1GB
HDD: WD Black 1TB
PSW: Corsair HX750W
DirectX Version: DirectX 12

**Comment by loganmc10** [comment]
I tested on Linux (Intel GPU), I have a laptop with Windows 10 and an Nvidia card, I'll test there and let you know

**Comment by loganmc10** [comment]
Does this only happen during the Winter/Lose screen? Or does it happen during the game as well? I only tested during gameplay

**Comment by Arisudomo** [comment]
Yup, it does happen during gameplay as well. Completely playable but with background, effects and some textures broken
![](https://cdn.discordapp.com/attachments/164547170756853760/380536074390470657/Untitled.jpg)

**Comment by loganmc10** [comment]
Just tested on Windows. The effects do get messed up for me, but not the background behind the tiles:

![puzzle_league_n64-002](https://user-images.githubusercontent.com/848146/32900565-fa91a786-caaa-11e7-916e-72e1dc6aaff8.png)

But that is an old issue with GLideN64 (https://github.com/gonetz/GLideN64/issues/315), not a recent regression

**Comment by Arisudomo** [comment]
Yes, this is an old issue with GLideN64. Hmm so this shouldn't be posted as an issue here?

**Comment by loganmc10** [comment]
Yes I'd it's specific to GLideN64 it's better to post an issue there
