### ISSUE TITLE
Crashes on loading ROM

### ISSUE THREAD

**Issue by KillThad** [m64p/mupen64plus-GLideN64#35]
Whenever I try loading a ROM, it just crashes. I've tried resetting everything, running as admin, changing the ROM, everything, but it still just crashes.

**Comment by KillThad** [comment]
I just tried using the emulator today. I'm running Windows 7 64-bit, but only an integrated GMA X4500.

**Comment by KillThad** [comment]
That's probably the issue.

**Comment by loganmc10** [comment]
I believe that GPU only supports OpenGL 2.1.

GLideN64 (the bundled GFX plugin) requires at least OpenGL 3.3, that is most likely your issue.

**Comment by KillThad** [comment]
Ah, okay. I'm gonna upgrade soon, so it isn't a big issue. Thanks for the help :)

**Comment by loganmc10** [comment]
no problem:)
