### ISSUE TITLE
Counter Factor in M64p??

### ISSUE THREAD

**Issue by 1DiDaDo1** [m64p/mupen64plus-GLideN64#39]
Is there an option in this emu like that? 
If so, i like to know if it is possible to change this to 1 in M64p? 

Conker Bad Fur Day is working way smoother with it. (All games are actually)

**Comment by loganmc10** [comment]
Yes it is called "CountPerOp", it's near the bottom of the core options.

It defaults to 0 which means "game default", which is typically 2. You can set it to 1 to override any game default

**Comment by 1DiDaDo1** [comment]
Thank you for your quick reply!!

Will try it, and thank you for this great emu package 👍
