### ISSUE TITLE
.zip/7z support

### ISSUE THREAD

**Issue by Cibomatto2002** [m64p/mupen64plus-GLideN64#4]
will there be .zip/7z support soon all of my roms are 7z?

**Comment by loganmc10** [comment]
This is probably the most requested feature I get, so I'll probably end up doing it soon. I plan on supporting zip and 7z, but nothing else (like rar). I can't really give you a timeline, but probably a week or two

**Comment by loganmc10** [comment]
This has been implemented, the latest version on https://m64p.github.io now supports zip and 7z files

**Comment by Cibomatto2002** [comment]
Thank you very much.
