### ISSUE TITLE
Current build generating corrupt save states?

### ISSUE THREAD

**Issue by delta7890** [m64p/mupen64plus-GLideN64#41]
Hi folks,

I'm running today's build (12/11/17) and it appears that the emulator is generating corrupt save states for me.  Loading old states works just fine, but any new save state I make currently will crash the emulator if I attempt to load them.

Not sure when this bug was introduced as today is my first day using this particular emulator package.

**Comment by loganmc10** [comment]
What game(s) did you test?

**Comment by delta7890** [comment]
Yoshi's Story, Diddy Kong Racing, and Banjo Kazooie all crash when loading a new save state.  Super Mario 64 seems to be unaffected.  I can test further if needed.

**Comment by loganmc10** [comment]
This should be fixed now, the buildbot is currently building the latest version, it should be all done in about 30 minutes, so you can download the latest version then.

The save states themselves are actually fine, it was just the code used for loading them that was broken, so there shouldn't be any corrupt save states (just FYI in case you needed to use one that you've created already)

**Comment by delta7890** [comment]
Awesome, glad this was fixed!
