### ISSUE TITLE
angrylion not included in latest 32 and 64-bit packages

### ISSUE THREAD

**Issue by SigmaVirus** [m64p/mupen64plus-GLideN64#43]
Happy Holidays @loganmc10 

There have been some changes to @ata4 angrylion-plus plugin that I wanted to test but as of https://github.com/m64p/mupen64plus-GLideN64/commit/6223187b08e6fa0e3e1b8bf9740e2f318f2e3fc4 the plugin is not included in either packages [here](https://m64p.github.io/)

Just wanted to inform you on that in case you forgot to include it or if there was build errors or something.

**Comment by SigmaVirus** [comment]
angrylion not included in https://github.com/m64p/mupen64plus-GLideN64/commit/832e318201ef921bbbcac0abef9d63a14d4d2145 either.

**Comment by loganmc10** [comment]
It is, you just need to give it a bit to build, it takes about 30 minutes to build both versions after I make a commit, the 64 bit version is probably already updated but the 32 bit version is probably still building (as of right now)

**Comment by SigmaVirus** [comment]
Yep, it's there now!

Thanks man for a super duper tremendous work!
