### ISSUE TITLE
Mupen64Plus not remembering window position?

### ISSUE THREAD

**Issue by delta7890** [m64p/mupen64plus-GLideN64#44]
Running on Windows 7 64-bit.  It's a small annoyance, but this program does not seem to remember its last window position.  Seems it likes to open smack dab in the middle of the screen.

**Comment by loganmc10** [comment]
I haven't ignored this, it should be pretty trivial to do and I hope to get it done in the next day or two

**Comment by loganmc10** [comment]
This has been implemented: https://github.com/m64p/mupen64plus-gui/commit/c8a6cafb87381b5923190fd5132704a295a88bcb
