### ISSUE TITLE
input errors on y-axis when using real n64 controller with the mayflash usb adapter.

### ISSUE THREAD

**Issue by RickSanchez86** [m64p/mupen64plus-GLideN64#47]
Something has to be wrong in the input sdl in every release since Halloween. I found a workaround through simply copying over the audio sdl from the October 31th release into the new releases. But could look into it? I tested Waverace 64 and could not do any stunts exept the "barrel roll" because of the error. The stick randomly jumps up and down. (which also can be observed in the menu)

Oh yeah and the Start Button and Z Button are switched in the InputAutoCfg.ini (Button 8 and 9)

**Comment by steppres** [comment]
I managed to get fairly accurate mapping by editing InputAutoCfg.ini and changing:
`AnalogPeak = 20000,20000`
Under the 
`[Win32: USB GamePad]`
section. Seems like that setting has the wrong values for Win32 (but not Mac or Linux).

**Comment by loganmc10** [comment]
Thanks for reporting this. The input is managed by this plugin:

https://github.com/mupen64plus/mupen64plus-input-sdl

Can you open an issue or pull request there?

Also, it seems like someone else has also reported the Z and Start buttons being switched: https://github.com/mupen64plus/mupen64plus-input-sdl/issues/44, you could possibly just add a "me too" comment to that issue?
