### ISSUE TITLE
GLideN64 3.0 Update not working?

### ISSUE THREAD

**Issue by Multigunz** [m64p/mupen64plus-GLideN64#49]
Hi,

I sincerely apologize for my ignorance here, and I don't mean to clog down your github issue area with questions, but I didn't know where else to ask. I noticed that Mupen64plus is using GLideN64 2.0 rather then 3.0 (via Mupen's log). If I understand correctly, GLideN64 3.0 comes with a .dll for Mupen that is named the same as the one that comes with Mupen64plus (mupen64plus-video-GLideN64). There is also a GLideN64.custom.ini that matches up with the one Mupen64plus has installed in it's main directory. 

If I put the 3.0 GLidenN64 dll and .ini in the same location as the 2.0 plugin, Mupen64plus comes back as saying no video plugin detected. Am I doing something wrong or is there more going on behind the scenes that is causing the incompatibility?

**Comment by loganmc10** [comment]
The version of GLideN64 that is included is newer than 3.0, it's always the latest code available. You can ignore the version reported in the log (I'll look into why it says that, but it's wrong)

The 3.0 GLideN64 DLL that gonetz distributes is 32 bit, so you can't use it with the 64 bit version of mupen64plus

**Comment by Multigunz** [comment]
Wow! Thanks for the update and the obvious hard work (also explains why Mupen's .dll is much larger in size then that of GlideN64). I'll go ahead and close the dealio here. Thank you again.
