### ISSUE TITLE
avg antivirus blocks Emulator

### ISSUE THREAD

**Issue by Cibomatto2002** [m64p/mupen64plus-GLideN64#5]
avg antivirus blocks the emulator so I have to disable it to run the emulator. 
![capture8-16-2017-12 16 16 pm](https://user-images.githubusercontent.com/21169038/29376041-c9de9282-827c-11e7-8786-7bd499f50489.jpg)

**Comment by Z4st4m** [comment]
It's a false alarm from your Anti Vir, you can check these 2 files at virustotal website yourself.

https://www.virustotal.com/de/file/3aed69fd04fc30d6c729a79d872bba4551b5bd2d375fa864c6f1029ed3cdd7cd/analysis/1502908172/

**Comment by loganmc10** [comment]
Yeah I've never of an issue like this before. Tomorrow I'll file an issue with AVG to try and get them to clear it up.

**Comment by loganmc10** [comment]
I contacted AVG about this. There is not much more I can do besides that unfortunately. I didn't really hear back from them.

**Comment by Cibomatto2002** [comment]
I guess this is what you get when getting a free Anti Virus.
