### ISSUE TITLE
Close Emulator on ROM Exit option? <-- Not an Issue

### ISSUE THREAD

**Issue by Circelgod** [m64p/mupen64plus-GLideN64#50]
If I was to exit the ROM via escape. I was wondering if there is\could be an option to exit the emulator as well?

**Comment by loganmc10** [comment]
There is a commandline option for this, its the ```--nogui``` option. So if you launch the program like "mupen64plus-gui.exe --nogui", or "mupen64plus-gui.exe --nogui /path/to/rom.n64", then it'll remove all the GUI elements, and close the emulator when the ROM closes. Useful when using it with a frontend like LaunchBox or something. Is that what you're looking for?

**Comment by Circelgod** [comment]
That is exactly it! Thanks man! 

    On Tuesday, January 23, 2018 2:17 PM, Logan <notifications@github.com> wrote:
 

 There is a commandline option for this, its the --nogui option. So if you launch the program like "mupen64plus-gui.exe --nogui", or "mupen64plus-gui.exe --nogui /path/to/rom.n64", then it'll remove all the GUI elements, and close the emulator when the ROM closes. Useful when using it with a frontend like LaunchBox or something. Is that what you're looking for?—
