### ISSUE TITLE
Latest build doesn't pack a core

### ISSUE THREAD

**Issue by fzurita** [m64p/mupen64plus-GLideN64#51]
It seems like the latest build somehow didn't pack the core for at least Windows 32 and 64 bit zip files.

**Comment by loganmc10** [comment]
Yes it's because of this:

https://github.com/mupen64plus/mupen64plus-core/pull/529

The build broke, it's a pretty primitive buildbot so it uploaded the zip without the core

**Comment by fzurita** [comment]
Gotcha, you may want to change that so that it only uploads a new zip file if all binaries build successfully.

That way people don't have to go hunting for older versions when they are trying to download the app.

**Comment by loganmc10** [comment]
Yeah, next time I'm in front of my computer I'll revert the latest commit so it builds the old working one for now

**Comment by loganmc10** [comment]
Actually now that I think about it, reverting the commit won't fix the problem. It's something that has changed with MinGW, so I need that PR to get merged before the builds will work again. Unfortunately I don't keep the old builds

**Comment by fzurita** [comment]
Hmm.. interesting, in wonder if MiniGW knows about the breakage.

**Comment by loganmc10** [comment]
It seems like they just switched from using Unix style line endings to Windows style line endings, so it's not really a big, it's just that our Makefile only accounts for Unix style line endings currently

**Comment by loganmc10** [comment]
fixed now
