### ISSUE TITLE
"Couldn't load core library, please set the path in settings."

### ISSUE THREAD

**Issue by adabo** [m64p/mupen64plus-GLideN64#52]
This error started happening recently. It happens after trying to load a rom. The message appears twice then Mupen crashes.

I looked at the log and it said it was looking for "mupen64plus.dll", so I downloaded it from the Mupen64Plus repo and put it in the correct path, but the error still appears.

The strange thing is that this error did not show and Mupen ran fine on the same tablet previously. Any thoughts?

Windows 10 Pro
Surface Pro i5 7300U
4Gb RAM
Intel HD Graphics 620

**Comment by loganmc10** [comment]
Yes this is the same as this issue:

https://github.com/m64p/mupen64plus-GLideN64/issues/51

I submitted a patch to mupen64plus to fix this issue (https://github.com/mupen64plus/mupen64plus-core/pull/529) I'm just waiting for it to be merged

**Comment by adabo** [comment]
Oh nice. Right on then. Do you expect it to be a long wait? Curious, no rush.

**Comment by loganmc10** [comment]
It's hard to say, it just needs to be merged by one of the mupen64plus developers, I'll post here when it's done

**Comment by adabo** [comment]
Very well. I appreciate your help.

**Comment by loganmc10** [comment]
Ok I just push the commit that should fix this. The buildbot will take about 30 minutes to build both Windows versions, so you should be able to download it in 30-45 minutes
