### ISSUE TITLE
Gauntlet Legends glitches

### ISSUE THREAD

**Issue by OtavioRaposo** [m64p/mupen64plus-GLideN64#54]
Using GlideN64 with "Restore All Settings", Gauntlet Legends display glitches as you walk by the initial chamber (the characters and other graphics go black and flick, fire and magic sprites becomes bigger, pixelated and without transparency).

Graphics mostly are ok at the first level thought.

EDIT: I perceived that the glitches go away as you hide the swamp and snow gates from the screen.

**Comment by loganmc10** [comment]
Yes this is an issue with GLideN64, I've filed a bug report with them here: https://github.com/gonetz/GLideN64/issues/1705
