### ISSUE TITLE
007 Golden Eye (PAL) not working

### ISSUE THREAD

**Issue by OtavioRaposo** [m64p/mupen64plus-GLideN64#55]
Self explanatory title:

007 Golden Eye (USA) and (Japan) are working but (Europe) is not working.
All of the tested ROMs are No-Intro.

**Comment by loganmc10** [comment]
Can you share the details about the ROM you are testing, if you open the ROM, then go to ```Emulation->View Log``` will have something like this:

```
Core: Goodname: GoldenEye 007 (E) [!]
Core: Name: GOLDENEYE           
Core: MD5: CFF69B70A8AD674A0EFE5558765855C9
Core: CRC: 0414CA61 2E57B8AA
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1447
Core: Manufacturer: Nintendo
Core: Country: Europe (0x50)
```

That is the information for the PAL ROM I tested, and it seems to work without issue

**Comment by OtavioRaposo** [comment]
Sorry, Logan, you can close the issue. I just discovered using Total Commander that for some reason I've many corrupted ROMs, with 007 Golden Eye (Europe) being one of them.
