### ISSUE TITLE
[angrylion-plus] Taking screenshot is broken

### ISSUE THREAD

**Issue by rez-** [m64p/mupen64plus-GLideN64#59]
Unfortunately, taking a screenshot with F12 crashes the application (build date: 22 jan 2018) with angrylion-plus GFX plugin

**Comment by loganmc10** [comment]
If it just happens with angrylion-plus the bug should be reported here: https://github.com/ata4/angrylion-rdp-plus/issues

**Comment by rez-** [comment]
ok I was unsure, will do:)
