### ISSUE TITLE
Mario 64 doesn't load it's attract mode

### ISSUE THREAD

**Issue by Tasosgemah** [m64p/mupen64plus-GLideN64#61]
I found this issue in the latest version of m64p, older versions didn't have this.

Basically, you get Mario's head but the game never changes to show it's gameplay demonstration. Normally it should show some gameplay and then go back to Mario who says "press start to play" but it never happens. Kinda weird and new issue this one...

**Comment by loganmc10** [comment]
Like it just stays at the head forever, not frozen, just a moving head? That is very strange

**Comment by Tasosgemah** [comment]
Yes, Mario is moving his head normally and even starts to sleep (like normal) but then wakes up and continues this loop (not normal).

**Comment by loganmc10** [comment]
I just tested and couldn't reproduce, it sat at the head for a bit, then it switched to the gameplay footage. Do you have any non-default settings set?

**Comment by Tasosgemah** [comment]
Not for Super Mario, no. I only have some non-default settings for a few games via the custom GlideN64 ini. And my controller settings from before.

You are right though. I tested on a fresh setup and can't reproduce the issue. So i guess i have to re-configure from start since upgrading from a previous version seems to cause such issues.

**Comment by TheLocoBandito** [comment]
Seems to work as intended, tried with a build from 9th of March with cxd4 & angrylion-rdp-plus.
Perfect loop with both head and game play demos!

**Comment by Tasosgemah** [comment]
Yeah, a fresh install fixed this. Somehow, my previous cfg with the newer build caused it. I have no idea how. But this issue can be closed.
