### ISSUE TITLE
Original Audio SDL Build

### ISSUE THREAD

**Issue by Papermanzero** [m64p/mupen64plus-GLideN64#64]
Could you bundle the original SDL plugin beside your SDL2 plugin?
The original mupen64 plugin has some further options like audio sync or quality.

https://github.com/mupen64plus/mupen64plus-audio-sdl

**Comment by loganmc10** [comment]
The original SDL plugin doesn't work on Windows currently so I won't be including it. SDL2 always does "best" quality resampling so I don't think an option is really required there.

I've considered implementing audio sync in the SDL2 plugin but I don't really see the benefit. If someone had an example of a game that benefit from it I'd consider putting in the time to implement it.

**Comment by Papermanzero** [comment]
Strange, because I get some audio drop outs and noise compared to the original plugin (well at least with the version that was working).

**Comment by loganmc10** [comment]
Closing since this isn't an option, doesn't work with Windows
