### ISSUE TITLE
Window size and fullscreen mode

### ISSUE THREAD

**Issue by Papermanzero** [m64p/mupen64plus-GLideN64#65]
If the user activates fullscreen, thw window also changes the size.
Also if the user switches to fullscreen the window will change its size.
The main window shall remain in the size independet of the fullsceen settings.

**Comment by loganmc10** [comment]
I'm not sure what you mean? When you enter full screen, the window is basically maximized, what do you expect to happen?

**Comment by Papermanzero** [comment]
This seems to be the issue.
You are maximasing the window but you are not using an exclusiv fullscreen mode.
Well, the window itself is a smaller frame in the middle of the desktop. If I open a game the window size becomes as large as the set up resolution. Means if I leave the fullscreen mode, I have an huge window, which I have to shift to change settings.
I would expect (like other programs or emulators) that the size of the window is unchanged if I enter the fullscreen mode. However after leaving fullscreen mode the window size equals the fullscreen resolution.

**Comment by Papermanzero** [comment]
Here two screenshots.

Before I open a game:
![unbenannt](https://user-images.githubusercontent.com/10263536/38175734-65b42786-35e1-11e8-84b7-86adf3596d62.jpg)

After I opened a game in fullscreen mode:
![unbenannt2](https://user-images.githubusercontent.com/10263536/38175739-75f7af96-35e1-11e8-993c-d3cfa5f6ca28.jpg)

**Comment by loganmc10** [comment]
Maybe I'm misunderstanding your problem, but I can't see any issue. If I open a game in window mode, I can resize the window to some other size. Then I can enter full screen, and exit full screen, and the window will returned to my resized size. I don't see any problems.

**Comment by Papermanzero** [comment]
I do not have this behaviour. In my case, I do not return to the resized window. If I leave the fullscreen mode, my window will be very large (as screenshot 2 demonstrates). So the window size is different after I entered the fullscreen mode.

**Comment by Papermanzero** [comment]
You have to change your settings. I can reproduce your behavior.
You have to change in Video General the setting to start in full screen.
Then you can reproduce the issue, if you leave the fullscreen view to go back to window mode.

**Comment by Papermanzero** [comment]
Do not hit alt enter. Hit immidiately esc

**Comment by loganmc10** [comment]
> If I am in fullscreen and hit "Esc" to end the game, it reverts to a gray 640x480 window

**Comment by Papermanzero** [comment]
I will create a video ;-)

**Comment by Jj0YzL5nvJ** [comment]
That is a typical high DPI display bug. Change back to DPI's defaults, log out and try again.

**Comment by Papermanzero** [comment]
Tried the DPI approach but without success (I tried to deactivate the windows settings and to activate the native DPI setting in the application settings). :-(

Here a video about the issue:
https://youtu.be/ip5q7Xbq1Yg

I think it has something to do with the rendering. because you can see that the windows frame is getting bigger after I started the rom.
