### ISSUE TITLE
Portable Mode 

### ISSUE THREAD

**Issue by Papermanzero** [m64p/mupen64plus-GLideN64#66]
Currently the cfg file for mupen is stored in the users home folder (depending on the os, in windows for example in the roaming folder). It would be convinient if the config and all settings are stored within the emulator folder, so that you could use the emulator on portable storage devices.

**Comment by loganmc10** [comment]
If you go Settings->Plugin and Path Settings there is an option called "Config Dir Path". If you set that to "./", it'll be "portable mode" and it will put the config file in the same directory as the EXE

**Comment by Papermanzero** [comment]
Thanks. I thought this is the m64p config. Great to know and very handy.
