### ISSUE TITLE
mupen64plus-GLideN64 - AndroidTV

### ISSUE THREAD

**Issue by elcorsico** [m64p/mupen64plus-GLideN64#7]
Can you carry this sublime emulator
So that it is compatible androidtv
thanks for this
hello from France ;-)

**Comment by loganmc10** [comment]
This is what you want:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by elcorsico** [comment]
thanks logan

but in my android tv the plugin NGLide are bad
texture no correct

thanks reply
regards


-----E-mail d'origine-----
De : Logan <notifications@github.com>
A: m64p/mupen64plus-GLideN64 <mupen64plus-GLideN64@noreply.github.com>
Cc: elcorsico <m10298@aol.com>; Author <author@noreply.github.com>
Envoyé le : Sa, 19 Aoû 2017 14:17
Sujet : Re: [m64p/mupen64plus-GLideN64] mupen64plus-GLideN64 - AndroidTV (#7)



This is what you want:
https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by loganmc10** [comment]
Sorry, there is nothing I can provide that would be better than the link I provided.
