### ISSUE TITLE
Pokemon Stadium Flickering/Missing Pokemon Textures

### ISSUE THREAD

**Issue by garagesailor** [m64p/mupen64plus-GLideN64#72]
When playing Pokemon Stadium inside of a battle the Pokemon begin to blink or all together disappear. Displays fine temporarily if I switch from full screen to windowed, until next turn in the battle then back to flickering/disappearing, 

The game is running on default settings. Other games run fine.

System Info:
Win 10 v 1709
16GB ddr3 ram
i7-4770k
gtx 1070 ti
samsung 951 nvme m.2

**Comment by loganmc10** [comment]
I can reproduce this, I'll track down the bad commit

**Comment by loganmc10** [comment]
Fixed now
