### ISSUE TITLE
Can i use this Emulator with a Mayflash Gamecube Adapter?

### ISSUE THREAD

**Issue by Turaltay** [m64p/mupen64plus-GLideN64#75]
Hello and thank you for this great N64 Emulator,

I am using this Emulator with a Windows 10 (64 Bit) OS. The problem is that i can't set the buttons for my 2-Port Mayflash Gamecube Adapter (Version 3.87). My Adapter is shown in the device section as "MAYFLASH GameCube Controller Adapter (0)" and  "MAYFLASH GameCube Controller Adapter (1)". If i try to set any button, as example the A Button, it automatically changes it to "axis(4-)". Do i need to change the settings in the InputAutoCfg? If yes, what do i need to change?

**Comment by loganmc10** [comment]
They all get changed to axis 4- or only the A button? Some buttons register as an axis

**Comment by Turaltay** [comment]
Yes, they all get changed to axis 4-, except X Axis and Y Axis.

**Comment by loganmc10** [comment]
hm ok this will be tricky for me to figure out since I don't have that controller. Can you try: http://m64py.sourceforge.net/ and let me know if you have the same issue there?

**Comment by Turaltay** [comment]
Thank you for the link. Same problem with that emulator. Now it changes all buttons to axis(5+). It seems to be a incompability with mupen64, because the adapter always worked with other games and project64.

**Comment by loganmc10** [comment]
Ok then what I would do is open an issue here:

https://github.com/mupen64plus/mupen64plus-input-sdl

That is the input plugin that is used for mupen64plus, that would be a more appropriate place for this issue, and someone may see it there that may be able to help.
