### ISSUE TITLE
Libretro Sync

### ISSUE THREAD

**Issue by Papermanzero** [m64p/mupen64plus-GLideN64#78]
Would it be possible to sync this repository with the mupen64plus repository from libretro?
https://github.com/libretro/mupen64plus-libretro

It would be great to see m64p and its features as libretro core. =)

**Comment by loganmc10** [comment]
Unfortunately it's not that simple, it would take a great deal of work, and I personally don't have the time or motivation to take on that project.

But either way, it would be work that needs to be done in the libretro repo, so I'll close this ticket, but you can open one there if one doesn't already exist

**Comment by Papermanzero** [comment]
Thanks Logan. This is what I wanted to know.

**Comment by Oggom** [comment]
For what it's worth someone created a bounty for this:

https://github.com/libretro/mupen64plus-libretro/issues/57
