### ISSUE TITLE
Controller buttons "sticking" on config. Esc key not ending emulation.

### ISSUE THREAD

**Issue by normchomsky** [m64p/mupen64plus-GLideN64#79]
Hi, I'm using a PS4 controller. Every time I tried to config it some of the buttons were behaving strangely.
The first input is fine every time. Then for example: I go to config the left D-pad button after I have done the right and the box saying "input l-dpad" flashes for a second and fills it with the previous input, which is R-dpad. This happens even when nothing is pressed on the controller.

However if I hold the correct dpad direction and click to change it at the same time, it will override the issue.  This does not work for every input, square, x, circle, triangle, option and share will not override when held at the same time of clicking to change it. 

Sometimes it will put a random input into the box when trying this, I noticed it was only doing it with inputs I had already (pressed) tried on that session.

I am using manual input with "wireless controller 0" selected and wired checked. To fully config I had to input one at a time closing the app each time.

Also escaping doesn't always close the emulation. It's like 1 in 5 times it happens.
Edit: The escape key issue is solved if I click the mouse, windows key or anything else that isnt to do with the emulation. 

I love this emulator by the way.

**Comment by normchomsky** [comment]
The escape key issue is fine inside LB with the --nogui command line. That's what I was intending to use it for, and I found a work around for the controller config issue so I will close this. But if anyone has any questions just leave a comment.

**Comment by loganmc10** [comment]
The escape key thing is a window focus issue, it will only register the escape key if the window has focus.

For the controller, it is a legitimate issue, I'm going to close this in favor of #93 since it is a little more clearly worded and it is the same issue
