### ISSUE TITLE
Body Harvest ground tile texture issue

### ISSUE THREAD

**Issue by subenji** [m64p/mupen64plus-GLideN64#83]
Body Harvest is working fantastic - more accurate than any other setup I've tried before now. 
However, there is this texture rotation issue on the ground tiles.
Here's how the ground is supposed to look:
![mupen64plus-gui_2018-07-09_19-48-27](https://user-images.githubusercontent.com/8143051/42470177-962beafc-83b1-11e8-96af-4477ce3d753d.png)

But after passing over the area with the camera close to the ground, the textures get rotated:
![mupen64plus-gui_2018-07-09_19-49-08](https://user-images.githubusercontent.com/8143051/42470276-e14fe326-83b1-11e8-8945-82871b96c92c.png)

This happens across the entire game world, but a road makes it somewhat obvious what's happening.
I tested this after resetting all plugin settings.

**Comment by Jj0YzL5nvJ** [comment]
Could you please provide a savestate?

**Comment by subenji** [comment]
`Core: Goodname: Body Harvest (U) [!]
Core: Name: BODY HARVEST        
Core: MD5: 3B8585ED03E8DDB89D7DE456317545E7
Core: CRC: 5326696F FE9A99C3
Core: Imagetype: .z64 (native)`
GoodN64: "fabbdf02 7b878c56 Body Harvest (U) [!] (L-12582912)|bbb6666f 5014a473 747ee414 5f036d9f b25d7348|f61c30bc 6feaac97 00578a86 5d552ae4 2079b0e5"

Before corruption:
[Body Harvest st0[before].zip](https://github.com/m64p/mupen64plus-GLideN64/files/2179987/Body.Harvest.st0.before.zip)

After corruption:
[Body Harvest st1[after].zip](https://github.com/m64p/mupen64plus-GLideN64/files/2179989/Body.Harvest.st1.after.zip)

**Comment by loganmc10** [comment]
Does this happen with the included Angrylion plugin or only on GLideN64?

**Comment by loganmc10** [comment]
Ok I would file this bug on the GLideN64 issue page then, it'll get a better response there
