### ISSUE TITLE
m64p on Linux

### ISSUE THREAD

**Issue by OtavioRaposo** [m64p/mupen64plus-GLideN64#84]
Tried running m64p on Linux, but it gives me the following error...

./mupen64plus-gui: error while loading shared libraries: libminizip.so.1: cannot open shared object file: No such file or directory

**Comment by loganmc10** [comment]
What distribution is this?

**Comment by OtavioRaposo** [comment]
Linux Mint 19 Cinamon

**Comment by OtavioRaposo** [comment]
Isn't the file just missing in the zip?

**Comment by loganmc10** [comment]
No, the Linux bundle doesn't include those files, you need to install libminizip, I'm not sure exactly what it's called on Ubuntu, something like ```apt-get install libminizip``` will probably work
