### ISSUE TITLE
GlideN64 custom config does not load

### ISSUE THREAD

**Issue by Papermanzero** [m64p/mupen64plus-GLideN64#85]
I added following config to the GlideN64.custom.ini.

[SUPER%20MARIO%2064]
Good_Name=Super Mario 64 (E)
frameBufferEmulation\enableOverscan=1
frameBufferEmulation\overscanPAL\top=20
frameBufferEmulation\overscanPAL\bottom=24
frameBufferEmulation\overscanPAL\left=4
frameBufferEmulation\overscanPAL\right=4

However it seems Super Mario 64 (PAL Version) does not recognize the config.

**Comment by loganmc10** [comment]
It should look like this:

```
frameBufferEmulation\EnableOverscan=1
frameBufferEmulation\OverscanPalTop=20
frameBufferEmulation\OverscanPalBottom=24
frameBufferEmulation\OverscanPalLeft=4
frameBufferEmulation\OverscanPalRight=4
```

I believe it is case sensitive as well
