### ISSUE TITLE
Latest build does not include GlideN64

### ISSUE THREAD

**Issue by AriaHiro** [m64p/mupen64plus-GLideN64#89]
seems kinda weird not to include the plugin that people are going to want to use

**Comment by loganmc10** [comment]
Yes seems to be an issue with the Windows buildbot, the Linux build is still working.

I'll look into it tomorrow

**Comment by loganmc10** [comment]
@AriaHiro Should be fixed now, as suspected there is some bug with the buildbot, nothing wrong with the code. I had to change the compiler that is used to build GLideN64, but it looks like its working now.

Can you re-download and let me know?

**Comment by AriaHiro** [comment]
![the_legend_of_zelda-050](https://user-images.githubusercontent.com/14143827/45407601-e8345380-b637-11e8-93ed-f198ee90edc3.png)
works
