### ISSUE TITLE
Crash after pressing Return/Enter key in the settings windows.

### ISSUE THREAD

**Issue by valcheeky** [m64p/mupen64plus-GLideN64#9]
Going into the settings and clicking on any of the dialogs with keyboard input available and pressing the Enter key crashes the application.
![1](https://user-images.githubusercontent.com/29753802/30094581-cac93e60-9292-11e7-824d-02c3f0ee695a.PNG)
It only happens in settings similar to the highlighted in the image, settings that can be changed by input not settings that have checkmarks boxes like "SWAP_CHANNELS" 
it's not necessary to change the settings at all just click on the input box as if you were to change the value inside of it and press Enter.
After a crash the video-general and video settings are all blank until a game is run by the way.
![2](https://user-images.githubusercontent.com/29753802/30094721-829cdc90-9293-11e7-9d81-1e387d7ec869.PNG)

Changing a value and then closing the windows works fine.

Windows 10 64bit, using the 32bit build from https://m64p.github.io/

**Comment by loganmc10** [comment]
Thanks for reporting this, should be fixed now, the updated build is available on the site.

**Comment by valcheeky** [comment]
Thanks, it works fine now.
