### ISSUE TITLE
x64 build (mupen64plus-video-GLideN64.dll missing)

### ISSUE THREAD

**Issue by notcompute** [m64p/mupen64plus-GLideN64#96]
please do not close this issue every time.
i only tring to help,

in the x64 build the mupen64plus-video-GLideN64.dll missing

**Comment by loganmc10** [comment]
> in the x64 build the mupen64plus-video-GLideN64.dll missing

Thank you, this is useful detailed information

**Comment by loganmc10** [comment]
Should be fixed now
